version: "3.9"
services:
  multisetups:
    build:
      context: ./
    volumes:
      - type: bind
        target: /ceremony
        source: ${CEREMONY_DIR:-./ceremony}
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

volumes:
  ceremony:
